import { db } from '@/db';
import { menfessPosts } from '@/db/schema';

async function main() {
    const samplePosts = [
        // Crush posts (8 posts)
        {
            nickname: 'Secret Admirer',
            target: 'si rambut ikal kelas sebelah',
            category: 'crush',
            content: 'Hai target, kamu cantik banget hari ini! Serius deh, senyum kamu bikin hari ku cerah ☀️',
            mood: 'happy',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #001',
            ipAddress: '192.168.1.105',
            deviceInfo: 'Chrome/Windows',
            likesCount: 24,
            commentsCount: 8,
            createdAt: new Date('2024-12-15T10:30:00').toISOString(),
            updatedAt: new Date('2024-12-15T10:30:00').toISOString(),
        },
        {
            nickname: 'Pejuang Cinta',
            target: 'si rambut ikal',
            category: 'crush',
            content: 'To: si rambut ikal kelas sebelah. Gue udah suka sama lo dari semester kemarin tapi takut ngomong 😅',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #002',
            ipAddress: '192.168.1.87',
            deviceInfo: 'Safari/iPhone',
            likesCount: 42,
            commentsCount: 12,
            createdAt: new Date('2024-12-14T20:15:00').toISOString(),
            updatedAt: new Date('2024-12-14T20:15:00').toISOString(),
        },
        {
            nickname: 'Si Malu-Malu',
            target: 'crush',
            category: 'crush',
            content: 'Dear crush, tiap kali lo lewat depan kelas gue jadi nervous banget. Kapan berani nyapa ya? 💕',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #003',
            ipAddress: '192.168.2.43',
            deviceInfo: 'Chrome/Windows',
            likesCount: 38,
            commentsCount: 9,
            createdAt: new Date('2024-12-13T21:45:00').toISOString(),
            updatedAt: new Date('2024-12-13T21:45:00').toISOString(),
        },
        {
            nickname: 'Anonymous',
            target: 'temen sebangku',
            category: 'crush',
            content: 'Pengen banget ngajak makan bareng tapi takut ditolak huhu. Target pasti tau siapa dia 🙈',
            mood: 'baper',
            status: 'pending',
            isNightConfess: false,
            anonymousBadge: 'Anon #004',
            ipAddress: '192.168.1.92',
            deviceInfo: 'Firefox/Android',
            likesCount: 5,
            commentsCount: 2,
            createdAt: new Date('2024-12-17T13:20:00').toISOString(),
            updatedAt: new Date('2024-12-17T13:20:00').toISOString(),
        },
        {
            nickname: 'Anak Upacara',
            target: 'ketua OSIS',
            category: 'crush',
            content: 'Ganteng banget sih pake seragam OSIS, bikin salah fokus pas upacara 😳',
            mood: 'excited',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #005',
            ipAddress: '192.168.3.15',
            deviceInfo: 'Edge/Windows',
            likesCount: 31,
            commentsCount: 7,
            createdAt: new Date('2024-12-16T07:45:00').toISOString(),
            updatedAt: new Date('2024-12-16T07:45:00').toISOString(),
        },
        {
            nickname: 'Si Galau',
            target: 'dia',
            category: 'crush',
            content: 'Udah 3 bulan suka sama dia tapi dia kayaknya gatau gue exist wkwk sedih',
            mood: 'galau',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #006',
            ipAddress: '192.168.1.78',
            deviceInfo: 'Safari/iPhone',
            likesCount: 45,
            commentsCount: 15,
            createdAt: new Date('2024-12-15T22:30:00').toISOString(),
            updatedAt: new Date('2024-12-15T22:30:00').toISOString(),
        },
        {
            nickname: 'Anak Baris Belakang',
            target: 'anak baris depan',
            category: 'crush',
            content: 'Target selalu duduk di baris depan, gue selalu perhatiin dari belakang. Someday gue bakal ngomong!',
            mood: 'excited',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #007',
            ipAddress: '192.168.2.99',
            deviceInfo: 'Chrome/Windows',
            likesCount: 27,
            commentsCount: 6,
            createdAt: new Date('2024-12-14T11:15:00').toISOString(),
            updatedAt: new Date('2024-12-14T11:15:00').toISOString(),
        },
        {
            nickname: 'Jantungan',
            target: 'si cantik kantin',
            category: 'crush',
            content: 'Setiap ketemu di kantin jantung gue dag dig dug duer. Ini cinta atau sakit jantung ya? 💗',
            mood: 'excited',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #008',
            ipAddress: '192.168.1.54',
            deviceInfo: 'Firefox/Android',
            likesCount: 50,
            commentsCount: 13,
            createdAt: new Date('2024-12-16T19:50:00').toISOString(),
            updatedAt: new Date('2024-12-16T19:50:00').toISOString(),
        },
        
        // Curhat posts (8 posts)
        {
            nickname: 'Pejuang Tugas',
            target: null,
            category: 'curhat',
            content: 'Capek banget ngerjain tugas, deadline besok pagi tapi baru 30%. Tolong Tuhan 😭',
            mood: 'sad',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #009',
            ipAddress: '192.168.1.111',
            deviceInfo: 'Chrome/Windows',
            likesCount: 48,
            commentsCount: 14,
            createdAt: new Date('2024-12-16T23:45:00').toISOString(),
            updatedAt: new Date('2024-12-16T23:45:00').toISOString(),
        },
        {
            nickname: 'Anak MTK',
            target: null,
            category: 'curhat',
            content: 'Kenapa sih nilai MTK gue gak naik-naik padahal udah belajar mati-matian. Frustrated bgt!',
            mood: 'angry',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #010',
            ipAddress: '192.168.2.67',
            deviceInfo: 'Safari/iPhone',
            likesCount: 35,
            commentsCount: 11,
            createdAt: new Date('2024-12-15T14:20:00').toISOString(),
            updatedAt: new Date('2024-12-15T14:20:00').toISOString(),
        },
        {
            nickname: 'Anonymous',
            target: null,
            category: 'curhat',
            content: 'Temen deket gue mulai jauh semenjak dia punya pacar. Sedih rasanya ditinggalin 💔',
            mood: 'sad',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #011',
            ipAddress: '192.168.1.89',
            deviceInfo: 'Edge/Windows',
            likesCount: 41,
            commentsCount: 10,
            createdAt: new Date('2024-12-14T21:10:00').toISOString(),
            updatedAt: new Date('2024-12-14T21:10:00').toISOString(),
        },
        {
            nickname: 'Anak Harapan',
            target: null,
            category: 'curhat',
            content: 'Ortu gue strict banget soal nilai. Dapat 85 aja udah dimarahin. Capek jadi anak harapan keluarga',
            mood: 'angry',
            status: 'pending',
            isNightConfess: true,
            anonymousBadge: 'Anon #012',
            ipAddress: '192.168.3.22',
            deviceInfo: 'Chrome/Windows',
            likesCount: 3,
            commentsCount: 1,
            createdAt: new Date('2024-12-17T20:30:00').toISOString(),
            updatedAt: new Date('2024-12-17T20:30:00').toISOString(),
        },
        {
            nickname: 'Insomnia',
            target: null,
            category: 'curhat',
            content: 'Gabisa tidur mikirin tugas yang numpuk. Semester ini berat banget anjir 😩',
            mood: 'sad',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #013',
            ipAddress: '192.168.1.95',
            deviceInfo: 'Firefox/Android',
            likesCount: 39,
            commentsCount: 9,
            createdAt: new Date('2024-12-15T23:20:00').toISOString(),
            updatedAt: new Date('2024-12-15T23:20:00').toISOString(),
        },
        {
            nickname: 'Kesepian',
            target: null,
            category: 'curhat',
            content: 'Dijauhin temen sekelas gara-gara salah paham. Pengen jelasin tapi mereka udah gasuka duluan',
            mood: 'galau',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #014',
            ipAddress: '192.168.2.44',
            deviceInfo: 'Safari/iPhone',
            likesCount: 33,
            commentsCount: 8,
            createdAt: new Date('2024-12-13T15:40:00').toISOString(),
            updatedAt: new Date('2024-12-13T15:40:00').toISOString(),
        },
        {
            nickname: 'Anak B.Indo',
            target: null,
            category: 'curhat',
            content: 'Guru B.Indo kasih tugas analisis novel 20 halaman. TWENTY PAGES! Are you kidding me?!',
            mood: 'angry',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #015',
            ipAddress: '192.168.1.103',
            deviceInfo: 'Edge/Windows',
            likesCount: 44,
            commentsCount: 12,
            createdAt: new Date('2024-12-16T09:25:00').toISOString(),
            updatedAt: new Date('2024-12-16T09:25:00').toISOString(),
        },
        {
            nickname: 'Si Sendiri',
            target: null,
            category: 'curhat',
            content: 'Lagi galau parah, pengen cerita tapi gatau harus cerita ke siapa. Sendiri itu berat guys',
            mood: 'galau',
            status: 'pending',
            isNightConfess: true,
            anonymousBadge: 'Anon #016',
            ipAddress: '192.168.3.77',
            deviceInfo: 'Chrome/Windows',
            likesCount: 2,
            commentsCount: 0,
            createdAt: new Date('2024-12-17T22:15:00').toISOString(),
            updatedAt: new Date('2024-12-17T22:15:00').toISOString(),
        },
        
        // Humor posts (6 posts)
        {
            nickname: 'Si Lucu',
            target: null,
            category: 'humor',
            content: 'Guru matematika kita mirip Mr Bean wkwk gak bisa unsee sekarang 😂',
            mood: 'happy',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #017',
            ipAddress: '192.168.1.66',
            deviceInfo: 'Safari/iPhone',
            likesCount: 47,
            commentsCount: 15,
            createdAt: new Date('2024-12-14T12:30:00').toISOString(),
            updatedAt: new Date('2024-12-14T12:30:00').toISOString(),
        },
        {
            nickname: 'Anak Upacara',
            target: null,
            category: 'humor',
            content: 'Pas upacara bendera kepala gue dipake sarang burung sama pigeon. Worst Monday ever!',
            mood: 'happy',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #018',
            ipAddress: '192.168.2.88',
            deviceInfo: 'Firefox/Android',
            likesCount: 50,
            commentsCount: 13,
            createdAt: new Date('2024-12-16T08:00:00').toISOString(),
            updatedAt: new Date('2024-12-16T08:00:00').toISOString(),
        },
        {
            nickname: 'Comedy King',
            target: null,
            category: 'humor',
            content: 'Temen gue bilang dia laper, gue tawarinnya laper apa?. He said laper makan. Fair enough 🤣',
            mood: 'happy',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #019',
            ipAddress: '192.168.1.45',
            deviceInfo: 'Chrome/Windows',
            likesCount: 46,
            commentsCount: 11,
            createdAt: new Date('2024-12-15T19:40:00').toISOString(),
            updatedAt: new Date('2024-12-15T19:40:00').toISOString(),
        },
        {
            nickname: 'Anonymous',
            target: null,
            category: 'humor',
            content: 'POV: Lu lagi serius ngerjain ujian terus perut lu bunyi kenceng. Everyone stares. Pain.',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #020',
            ipAddress: '192.168.3.33',
            deviceInfo: 'Edge/Windows',
            likesCount: 49,
            commentsCount: 14,
            createdAt: new Date('2024-12-13T10:15:00').toISOString(),
            updatedAt: new Date('2024-12-13T10:15:00').toISOString(),
        },
        {
            nickname: 'Meme Lord',
            target: null,
            category: 'humor',
            content: 'Muka gue pas disuruh maju presentasi mendadak: 😀➡️😃➡️😐➡️💀',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #021',
            ipAddress: '192.168.1.101',
            deviceInfo: 'Safari/iPhone',
            likesCount: 43,
            commentsCount: 10,
            createdAt: new Date('2024-12-14T13:50:00').toISOString(),
            updatedAt: new Date('2024-12-14T13:50:00').toISOString(),
        },
        {
            nickname: 'Gamer',
            target: null,
            category: 'humor',
            content: 'Ketahuan guru lagi main game di kelas, hp disita. RIP my Clash Royale streak 😭😂',
            mood: 'sad',
            status: 'pending',
            isNightConfess: false,
            anonymousBadge: 'Anon #022',
            ipAddress: '192.168.2.55',
            deviceInfo: 'Firefox/Android',
            likesCount: 4,
            commentsCount: 2,
            createdAt: new Date('2024-12-17T11:30:00').toISOString(),
            updatedAt: new Date('2024-12-17T11:30:00').toISOString(),
        },
        
        // Random posts (5 posts)
        {
            nickname: 'Anak Bolos',
            target: null,
            category: 'random',
            content: 'Ada yang tau tugas B.Indo hari ini? Gue bolos kemarin soalnya sakit',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #023',
            ipAddress: '192.168.1.72',
            deviceInfo: 'Chrome/Windows',
            likesCount: 18,
            commentsCount: 7,
            createdAt: new Date('2024-12-16T07:20:00').toISOString(),
            updatedAt: new Date('2024-12-16T07:20:00').toISOString(),
        },
        {
            nickname: 'Anak Kantin',
            target: null,
            category: 'random',
            content: 'Kantin udah abis nasi goreng favorit gue. Ini baru jam 10 pagi anjir. Sad life.',
            mood: 'sad',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #024',
            ipAddress: '192.168.3.11',
            deviceInfo: 'Safari/iPhone',
            likesCount: 29,
            commentsCount: 8,
            createdAt: new Date('2024-12-15T10:05:00').toISOString(),
            updatedAt: new Date('2024-12-15T10:05:00').toISOString(),
        },
        {
            nickname: 'Broke Student',
            target: null,
            category: 'random',
            content: 'Rekomen dong tempat makan deket sekolah yang murah meriah. Uang jajan gue tinggal 20rb 😅',
            mood: 'nervous',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #025',
            ipAddress: '192.168.1.84',
            deviceInfo: 'Edge/Windows',
            likesCount: 34,
            commentsCount: 12,
            createdAt: new Date('2024-12-14T19:30:00').toISOString(),
            updatedAt: new Date('2024-12-14T19:30:00').toISOString(),
        },
        {
            nickname: 'Wibu',
            target: null,
            category: 'random',
            content: 'Siapa yang nonton anime Demon Slayer season terbaru? Gas diskusi!',
            mood: 'excited',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #026',
            ipAddress: '192.168.2.76',
            deviceInfo: 'Firefox/Android',
            likesCount: 26,
            commentsCount: 9,
            createdAt: new Date('2024-12-13T16:45:00').toISOString(),
            updatedAt: new Date('2024-12-13T16:45:00').toISOString(),
        },
        {
            nickname: 'Cari Duit',
            target: null,
            category: 'random',
            content: 'Info loker SPG/SPB dong untuk anak SMA, butuh duit jajan tambahan nih',
            mood: 'excited',
            status: 'pending',
            isNightConfess: false,
            anonymousBadge: 'Anon #027',
            ipAddress: '192.168.1.93',
            deviceInfo: 'Chrome/Windows',
            likesCount: 8,
            commentsCount: 3,
            createdAt: new Date('2024-12-17T14:00:00').toISOString(),
            updatedAt: new Date('2024-12-17T14:00:00').toISOString(),
        },
        
        // Motivasi posts (3 posts)
        {
            nickname: 'Motivator',
            target: null,
            category: 'motivasi',
            content: 'Semangat UAS guys! Ingat, hasil gak akan mengkhianati usaha. You got this! 💪',
            mood: 'excited',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #028',
            ipAddress: '192.168.1.58',
            deviceInfo: 'Safari/iPhone',
            likesCount: 50,
            commentsCount: 11,
            createdAt: new Date('2024-12-15T08:30:00').toISOString(),
            updatedAt: new Date('2024-12-15T08:30:00').toISOString(),
        },
        {
            nickname: 'Life Coach',
            target: null,
            category: 'motivasi',
            content: 'Bad day ≠ bad life. Besok adalah hari yang baru dengan kesempatan baru. Keep your head up! ✨',
            mood: 'happy',
            status: 'approved',
            isNightConfess: true,
            anonymousBadge: 'Anon #029',
            ipAddress: '192.168.2.91',
            deviceInfo: 'Edge/Windows',
            likesCount: 47,
            commentsCount: 10,
            createdAt: new Date('2024-12-16T20:45:00').toISOString(),
            updatedAt: new Date('2024-12-16T20:45:00').toISOString(),
        },
        {
            nickname: 'Supporter',
            target: null,
            category: 'motivasi',
            content: 'To everyone yang lagi struggle: it\'s okay to not be okay. Take your time, heal, and grow. We believe in you! 🌱',
            mood: 'happy',
            status: 'approved',
            isNightConfess: false,
            anonymousBadge: 'Anon #030',
            ipAddress: '192.168.1.77',
            deviceInfo: 'Firefox/Android',
            likesCount: 49,
            commentsCount: 13,
            createdAt: new Date('2024-12-14T15:15:00').toISOString(),
            updatedAt: new Date('2024-12-14T15:15:00').toISOString(),
        },
    ];

    await db.insert(menfessPosts).values(samplePosts);
    
    console.log('✅ Menfess posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});